### ISSUE TITLE
2) Lukáš: Invaders projectiles, spaceship hit function and HP

### ISSUE THREAD

**Issue by lukassofka** [KenkiCZ/E8_Space_invaders#2]
Už je pozdě na mě... Ale je potřeba udělat "nějak", aby invaders stříleli zpátky a potom vyhodnotit spaceship projectile collision.
K tomu se pojí i nějaké "srdíčka", HP cokoliv tohoto typu

**Comment by KenkiCZ** [comment]
Už je pozdě na mě... Ale je potřeba udělat "nějak", aby invaders stříleli zpátky a potom vyhodnotit spaceship projectile collision.
K tomu se pojí i nějaké "srdíčka", HP cokoliv tohoto typu
